name: 🐞 Bug Report
description: File a bug if something isn't working as expected.
labels: [bug, needs-triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the form below so we can fix it quickly.

  - type: input
    id: title
    attributes:
      label: Bug Summary
      placeholder: A short and clear title for the bug
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the issue, what you expected to happen, and what actually happened.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide a list of steps, commands, or code to reproduce the issue.
      placeholder: |
        1. Run `cargo run`
        2. Pass input "..."
        3. Observe the output
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Runefix CLI Version
      placeholder: e.g., 0.1.0

  - type: textarea
    id: logs
    attributes:
      label: Terminal Output / Error Logs
      description: Paste any error messages or logs here.
      render: shell
