blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a Question or Get Help
    url: https://github.com/runefix-labs/runefix-cli/discussions
    about: Ask usage questions, design feedback, or get help from the community.
